name: "Find and Replace"
description: "Replace substring with the another one"
inputs:
  find: 
    description: "String to be replaced"
    required: true
  replace:
    description: "Final string"
    required: false
    default: ""
  words_only:
    description: "Inputs to be considered as words or substring"
    required: false
    default: false
  regex-in-find:
    description: "Word given in 'find' to be considered as regex"
    required: false
    default: false
  regex-in-replace:
    description: "Word given in 'replace' to be considered as regex"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: "Escaped text in find"
      if: ${{ inputs.regex-in-find == true }}
      uses: thenbdev/escape-string@main
      id: escape-string-find
      with:
        text: ${{ inputs.find }}

    - name: "Escaped text in replace"
      if: ${{ inputs.regex-in-replace == true }}
      uses: thenbdev/escape-string@main
      id: escape-string-replace
      with:
        text: ${{ inputs.replace }}

    - name: "Find and Replace main"
      shell: bash
      run: |
        find_substring="${{ inputs.find }}"
        replace_substring="${{ inputs.replace }}"
        echo "Given find:"$find_substring
        echo "Given replace:"$replace_substring

        if [[ "${{ steps.escape-string-find.outputs.text == null }}" == "true" ]]; then
          find_substring="${{ inputs.find }}"
        fi
        echo "Using find text:"$find_substring


        if [[ "${{ steps.escape-string-replace.outputs.text == null }}" == "true" ]]; then
          find_substring="${{ inputs.replace }}"
        fi
        echo "Using replace text:"$replace_substring

        sed_replacement_string="$find_substring/$new_substring"
        if [[ "${{ inputs.words_only }}" == "true" ]]; then
          sed_replacement_string="\b"$sed_replacement_string
        fi
        echo $sed_replacement_string

        # Use sed to replace the substrings with the new string in all files in the current directory
        find . -type f -not -path '.git/*' -exec sed -i "s/$sed_replacement_string/g" {} +
