name: "Find and Replace"
description: "Replace substring with the another one"
inputs:
  find: 
    description: "String to be replaced"
    required: true
  replace:
    description: "Final string"
    required: false
    default: ""
    
runs:
  using: "composite"
  steps:
  
    - shell: bash
      run: |
        # Escape any forward slashes in the substrings
        old_substrings="$(<<< "${{ inputs.find }}" sed -e 's`[][\\/.*^$]`\\&`g')"

        # Use sed to replace the substrings with the new string in all files in the current directory
        find . -type f -exec sed -i "s/$old_substrings/${{ inputs.replace }}/g" ./* +
