name: "Find and Replace"
description: "Replace substring with the another one"
inputs:
  find: 
    description: "String to be replaced"
    required: true
  replace:
    description: "Final string"
    required: false
    default: ""
  words_only:
    description: "Inputs to be considered as words or substring"
    type: boolean
    required: false
    default: false
  ignore_case:
    description: "Ignore case when doing match"
    type: boolean
    required: false
    default: true
  regex-in-find:
    description: "Word given in 'find' to be considered as regex"
    type: boolean
    required: false
    default: false
  regex-in-replace:
    description: "Word given in 'replace' to be considered as regex"
    type: boolean
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: "Escaped text in find"
      if: ${{ inputs.regex-in-find == 'false' }}
      uses: thenbdev/escape-string@main
      id: escape-string-find
      with:
        text: ${{ inputs.find }}

    - name: "Escaped text in replace"
      if: ${{ inputs.regex-in-replace == 'false' }}
      uses: thenbdev/escape-string@main
      id: escape-string-replace
      with:
        text: ${{ inputs.replace }}

    - name: "Find and Replace main"
      shell: bash
      run: |
        echo ${{ inputs.regex-in-find == false }}
        echo ${{ inputs.regex-in-find == 'false' }}
        find_substring="${{ steps.escape-string-find.outputs.text }}"
        if [[ "$find_substring" == "" ]]; then
          find_substring="${{ inputs.find }}"
        fi
        echo "Using find text:"$find_substring

        replace_substring="${{ steps.escape-string-replace.outputs.text }}"
        if [[ "$replace_substring" == "" ]]; then
          replace_substring="${{ inputs.replace }}"
        fi
        echo "Using replace text:"$replace_substring

        if [[ "${{ inputs.words_only }}" == "true" ]]; then
          find_substring="\(^\|\s\)"$find_substring"\(\s\|$\)"
          replace_substring="\1"$replace_substring"\2"
          echo "Wrapper for word only search: "$find_substring", "$replace_substring
        fi
        sed_replacement_string="$find_substring/$replace_substring"
        echo $sed_replacement_string

        sed_params="/g"
        if [[ "${{ inputs.ignore_case }}" == "true" ]]; then
          sed_params="/Ig"
        fi

        # Use sed to replace the substrings with the new string in all files in the current directory
        find . -type f -not -path '.git/*' -exec sed -i "s/$sed_replacement_string$sed_params" {} +
